name: upi_mock_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  qr_code_scanner:
    git:
      url: https://github.com/juliuscanute/qr_code_scanner.git
      ref: master
    # <- downgrade to this
  intl: ^0.19.0
  encrypt: ^5.0.3
  http: ^1.2.2
  speech_to_text: ^7.0.0
  flutter_tts: ^3.8.5
  provider: ^6.1.2
  web_socket_channel: ^2.4.0
  google_mlkit_barcode_scanning: ^0.13.0
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.14.0
  razorpay_flutter: ^1.3.6
  shared_preferences: ^2.2.2
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  permission_handler: ^11.0.1
  flutter_local_notifications: ^17.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


